name: agendamento_barber
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  auto_size_text: ^3.0.0
  brasil_fields: ^1.15.0
  cached_network_image: ^3.4.1
  calendar_date_picker2: ^2.0.0
  cloud_firestore: ^5.6.6
  date_picker_plus: ^4.2.0
  email_validator: ^3.0.0
  file_picker: ^10.2.0
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  supabase_flutter: ^2.8.4
  url_launcher: ^6.3.2
  webviewx_plus: ^0.5.1
  flutter_localization: ^0.3.1
  mailer: ^6.4.1
  flutter_dotenv: ^5.2.1
  responsive_framework: ^1.5.1
  carousel_slider: ^5.0.0
  shimmer_animation: ^2.2.2
  go_router: ^16.0.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  xor_encryption: ^0.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - config.json
